# This is a basic workflow to help you get started with Actions

name: Pack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command the runners shell
      - name: Run the pack script
        run: chmod +x ./pack.sh && ./pack.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          path: |
            working_dir/x64dbg.zip
            working_dir/version.md
      
      - name: Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: working_dir/x64dbg.zip
          tag: ${{env.VERSION_HASH}}
          bodyFile: working_dir/version.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}